# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U22EElXIBL9anSQkQ0yE9jVT7aftc5Hn
"""

import numpy as np
import pandas as pd
import seaborn as sns

df=pd.read_csv("Unemployment in India.csv")

df.describe()

df.shape

df.info()

df.describe()

df.isnull().sum()

a=df.dropna()

a.tail()

a.isnull().sum()

sns.pairplot(a,hue='Area')

x = a['Region']

x

y=a[' Estimated Unemployment Rate (%)']
y

df2=a.iloc[:,3]
df2

import matplotlib.pyplot as plt
import plotly.express as px

fg = px.bar(a,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',template='plotly_dark')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.box(a,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',template='plotly_dark')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.scatter(a,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',template='plotly_dark')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()

fg = px.histogram(a,x='Region',y=' Estimated Unemployment Rate (%)',color='Region',template='plotly_dark')
fg.update_layout(xaxis={'categoryorder':'total descending'})
fg.show()